### ISSUE TITLE
/v2/account/valuation is missing

### ISSUE THREAD

**Issue by teland94** [JKorf/HTX.Net#102]
Hello. I think this https://www.huobi.com/en-us/opend/newApiPages/?id=7ec5058c-7773-11ed-9966-0242ac110003 is missing now.

Don't confuse with already implemented:
https://www.huobi.com/en-us/opend/newApiPages/?id=7ec4ff6d-7773-11ed-9966-0242ac110003

**Comment by JKorf** [comment]
Is available
