### ISSUE TITLE
account-frozen-account-inexistent-error

### ISSUE THREAD

**Issue by UncleJey** [JKorf/HTX.Net#118]
Has anybody same error?

trying

```
PlaceOrderAsync(
        accountId: XXXXXXXX,
        symbol: 'TONUSDT',
        side: OrderSide.Buy,
        type: OrderType.Market,
        quantity: 5.53,
        clientOrderId: "a001"

```

Having an error

> account-frozen-account-inexistent-error: account for id `XX,XXX,XXX` and user id `12,345,678` does not exist

but my user has a different number. One digit more.
like 12.345.678.9

is this a client or server error?

**Comment by JKorf** [comment]
Did you get the account id from the `restClient.SpotApi.Account.GetAccountsAsync` response?

**Comment by UncleJey** [comment]
yep. Getting id from 

```
        var acc = await restClient.SpotApi.Account.GetAccountsAsync();
        account = acc.Data.First();
        Debug.Log($"account id:{account.Id} status: {account.Status} type:{account.Type}");

```

**Comment by UncleJey** [comment]
in error 
account-frozen-account-inexistent-error: account for id XXXXXXXX
and my debug
account id:XXXXXXXX status: Working type:Spot

ids is same
