### ISSUE TITLE
Futures/Swaps support

### ISSUE THREAD

**Issue by ShakesB33r** [JKorf/HTX.Net#57]
It does not seem to me that futures or swaps support is available, unless I missed it. Are there any plans for implementation? Or if available, any examples?

**Comment by ShakesB33r** [comment]
Are you open to pull requests on this?

**Comment by JKorf** [comment]
Sorry for the late reaction, must've missed the notification. Yes, a PR for implementation for the Futues/swap API is much welcome.

**Comment by ngothanhluan** [comment]
Any update on this. @JKorf do you have a plan to support futures on Huobi?

**Comment by danielhw2** [comment]
I would love to use Futures on Huobi too....

**Comment by wecando168** [comment]
> I would love to use Futures on Huobi too....

This fork adds functionality to Huobi Contracts
https://github.com/wecando168/Huobi.Net-4.1.8

**Comment by danielhw2** [comment]
When futures? 🥲

**Comment by JKorf** [comment]
USDT-M futures/swaps have been available for a while, Coin-M futures will be added at a later time
