### ISSUE TITLE
Cannot subscribe to correct ticker

### ISSUE THREAD

**Issue by yetiwolf** [JKorf/HTX.Net#69]
I'm experienced with binance and kucoin implementations, but trying to integrate Huobi.

client.SubscribeToSymbolTickerUpdatesAsync returns HuobiSymbolDatas and those tickers don't have ask/bids.  I am not able to specify a coin name as the example here shows.  Am I missing how to subscribe to specific tickers w/ ask/bid or is the wrapper missing it?

**Comment by JKorf** [comment]
Cleaning up Github issues, I'm assuming this is no longer relevant
